databases:
  - name: odontolab-db
    databaseName: odontolab
    user: odontolab
    plan: free

services:
  - type: web
    name: odontolab-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300 --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: odontolab-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: true
      - key: ENVIRONMENT
        value: production
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: CORS_ORIGINS
        value: http://localhost:3000,http://localhost:8000